### PR TITLE
Fix passing multiple file descriptors / control messages via sendmsg

### LINKED ISSUE #464: Passing multiple FD over an Unix Socket in a single Control Message doesn't work
For some reason, passing multiple FD over a Unix Domain Socket doesn't seem to work. Below is some test code that is supposed to send two fd over a Unix Socket along with 8 bytes of data. For some reason, only one FD is sent though, the other is lost in the void.

```rust
extern crate nix;

use std::os::unix::net::UnixDatagram;
use std::os::unix::io::{RawFd, AsRawFd};
use nix::sys::socket::{CmsgSpace, ControlMessage, MsgFlags, sendmsg, recvmsg};
use nix::sys::uio::IoVec;


fn main() {
    let (send, receive) = UnixDatagram::pair().unwrap();
    let thread = std::thread::spawn(move || {
        let mut buf = [0u8; 8];
        let iovec = [IoVec::from_mut_slice(&mut buf)];
        let mut space = CmsgSpace::<[RawFd; 2]>::new();
        let (paneid, fds) = match recvmsg(receive.as_raw_fd(), &iovec, Some(&mut space), MsgFlags::empty()) {
            Ok(msg) => {
                let mut iter = msg.cmsgs();
                if let Some(ControlMessage::ScmRights(fds)) = iter.next() {
                    (iovec[0].as_slice(), fds.to_vec())
                } else {
                    panic!();
                }
            },
            Err(_) => {
                panic!();
            }
        };
        println!("paneid = {:?}, fds = {:?}", paneid, fds);
    });

    let slice = [1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8];
    let iov = [IoVec::from_slice(&slice)];
    let arr = [0, 1]; // Pass stdin and stdout
    let cmsg = [ControlMessage::ScmRights(&arr)];
    sendmsg(send.as_raw_fd(), &iov, &cmsg, MsgFlags::empty(), None).unwrap();
    thread.join().unwrap();
}
```

The output is `paneid = [1, 2, 3, 4, 5, 6, 7, 8], fds = [6]`

### LINKED ISSUE #756: Sending multiple ControlMessage in a single Unix Socket packet fails
This is a continuation of #464 and #473. For some reason, the attached test still fails.

IIRC, there's a problem in the way we encode multiple Control Messages which causes the kernel to only consider the first Control Message sent. The specifics of where the bug is, I have no idea.

<details>
<summary>The failing test</summary>

```rust
#[test]
fn test_scm_rights_multiple_cmsg() {
    use std::os::unix::net::UnixDatagram;
    use std::os::unix::io::{RawFd, AsRawFd};
    use std::thread;
    use nix::sys::socket::{CmsgSpace, ControlMessage, MsgFlags, sendmsg, recvmsg};
    use nix::sys::uio::IoVec;

    let (send, receive) = UnixDatagram::pair().unwrap();
    let thread = thread::spawn(move || {
        let mut buf = [0u8; 8];
        let iovec = [IoVec::from_mut_slice(&mut buf)];
        let mut space = CmsgSpace::<([RawFd; 1], CmsgSpace<[RawFd; 1]>)>::new();
        let (data, fds) = match recvmsg(receive.as_raw_fd(), &iovec, Some(&mut space), MsgFlags::empty()) {
            Ok(msg) => {
                let mut iter = msg.cmsgs();
                let fdone;
                let fdtwo;
                if let Some(ControlMessage::ScmRights(fds)) = iter.next() {
                    fdone = fds[0];
                } else {
                    panic!();
                }
                if let Some(ControlMessage::ScmRights(fds)) = iter.next() {
                    fdtwo = fds[0];
                } else {
                    panic!();
                }
                (iovec[0].as_slice(), [fdone, fdtwo])
            },
            Err(_) => {
                panic!();
            }
        };
        assert_eq!(data, [1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8]);
        assert_eq!(fds.len(), 2);
    });

    let slice = [1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8];
    let iov = [IoVec::from_slice(&slice)];
    let arrone = [0];
    let arrtwo = [1]; // pass stdin and stdout
    let cmsg = [ControlMessage::ScmRights(&arrone), ControlMessage::ScmRights(&arrtwo)];
    sendmsg(send.as_raw_fd(), &iov, &cmsg, MsgFlags::empty(), None).unwrap();
    thread.join().unwrap();
}
```

</details>

### PR DESCRIPTION
**Pull request by jonas-schievink**
Fixes #464
Closes #874 because it's incorporated here
Closes #756 because it adds the test from that issue (with fixes)

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Current CI failures:

* Only 1 fd was successfully received, the other got lost
  * FreeBSD x86_64
  * powerpc64-unknown-linux-gnu
  * powerpc64le-unknown-linux-gnu
  * mips64-unknown-linux-gnuabi64
  * mips64el-unknown-linux-gnuabi64
  * aarch64-unknown-linux-gnu
* `EINVAL`
  * i686-apple-darwin
  * x86_64-apple-darwin

**Comment by jonas-schievink** [comment]
**Every single** CI job that failed passes another test that *also* passes 2 fds, but only using a *single* control message. Seems like you're not supposed to use more than 1 `SCM_RIGHTS` message.

I've deleted the broken test and added a note.

File: test/test_pass_fds.rs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+            Ok(msg) => {
+                let mut iter = msg.cmsgs();
+                if let Some(ControlMessage::ScmRights(fds)) = iter.next() {
+                    (iovec[0].as_slice(), fds.to_vec())
+                } else {
+                    panic!();
+                }
+            },
+            Err(_) => {
+                panic!();
```
Comment (asomers) [inline test/test_pass_fds.rs]: These two panic messages are indistinguishable since you don't provide descriptions for them.  And if the error case is a simple `panic`, you may as well just use `unwrap` instead of `if let`.

File: test/test_pass_fds.rs [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+use nix::sys::uio::IoVec;
+
+
+fn main() {
+    let (send, receive) = UnixDatagram::pair().unwrap();
+    let thread = std::thread::spawn(move || {
+        let mut buf = [0u8; 8];
+        let iovec = [IoVec::from_mut_slice(&mut buf)];
+        let mut space = CmsgSpace::<[RawFd; 2]>::new();
+        let (paneid, fds) = match recvmsg(receive.as_raw_fd(), &iovec, Some(&mut space), MsgFlags::empty()) {
```
Comment (asomers) [inline test/test_pass_fds.rs]: What is a "paneid" ?

File: test/test_pass_fds.rs [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+            Err(_) => {
+                panic!();
+            }
+        };
+        println!("paneid = {:?}, fds = {:?}", paneid, fds);
+    });
+
+    let slice = [1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8];
+    let iov = [IoVec::from_slice(&slice)];
+    let arr = [0, 1]; // Pass stdin and stdout
```
Comment (asomers) [inline test/test_pass_fds.rs]: This should be `libc::STDIN_FILENO` and `libc::STDOUT_FILENO`.

File: test/sys/test_socket.rs [hunk 4]
```diff
@@ -167,6 +167,41 @@ pub fn test_scm_rights() {
...
+            _ => panic!(),
+        }
+        assert!(cmsgs.next().is_none(), "unexpected control msg");
+
+        assert_eq!(iovec[0].as_slice(), [1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8]);
+    });
+
+    let slice = [1u8, 2u8, 3u8, 4u8, 5u8, 6u8, 7u8, 8u8];
+    let iov = [IoVec::from_slice(&slice)];
+    let fds = [0, 1];    // pass stdin and stdout
```
Comment (asomers) [inline test/sys/test_socket.rs]: should be libc::STDIN_FILENO and libc::STDOUT_FILENO.

File: Cargo.toml [hunk 5]
```diff
@@ -50,3 +50,8 @@ harness = false
 [[test]]
 name = "test-ptymaster-drop"
 path = "test/test_ptymaster_drop.rs"
+
+[[test]]
```
[the remark this answers is not in the document]
Comment (jonas-schievink) [reply Cargo.toml]: Turns out the test I added in a recent commit essentially does the same thing (pass 2 fds using 1 cmsg), so I'll remove this one.

Adding examples to nix is a very good idea, but I guess it should be done as a more coordinated approach rather than in this PR.

**Comment by jonas-schievink** [comment]
> Does Nix also have a bug with sending two dissimilar control messages in a single sendmsg call, and if so does this change fix it?

This *should* fix that, but I haven't added a test since there's no convenient `ControlMessage` that can be used to test it. I might add support for `SCM_CREDENTIALS` later and use that along with `SCM_RIGHTS` to test this.

**Comment by asomers** [comment]
Why not use `ScmRights` with `ScmTimestamp`?

**Comment by jonas-schievink** [comment]
Attempting to send a `SCM_TIMESTAMP` results in `EINVAL` on my system (x64 Linux). Even when it's just a single `SCM_TIMESTAMP` control message, and even from C++, so it's not a bug in nix, you're just not supposed to send those by yourself (the kernel does).

**Comment by jonas-schievink** [comment]
@asomers Anything left to do here?

File: src/sys/socket/mod.rs [hunk 6]
```diff
@@ -287,18 +287,30 @@ impl fmt::Debug for Ipv6MembershipRequest {
...
-/// because it exposes all bytes in src, which may be UB if some of them
-/// are uninitialized (including padding).
-unsafe fn copy_bytes<'a, 'b, T: ?Sized>(src: &T, dst: &'a mut &'b mut [u8]) {
+/// Copy the in-memory representation of `src` into the byte slice `dst`.
+///
+/// Returns the remainder of `dst`.
+///
+/// Panics when `dst` is too small for `src` (panics if `mem::size_of_val(src) >= dst.len()`).
+///
+/// Unsafe because it exposes all bytes in `src`, which may be UB if some of them are uninitialized
```
Comment (asomers) [inline src/sys/socket/mod.rs]: It's not actually unsafe to read an uninitialized slice, because slices are always supposed to be initialized.  The unsafe part is creating the uninitialized slice in the first place.  However, it _is_ unsafe to call `copy_nonoverlapping` without verifying that the slices don't overlap, without verifying that `T` implements `Copy`, and without `drop`ing the contents of `dst`.  Please update the comment.

File: src/sys/socket/mod.rs [hunk 7]
```diff
@@ -287,18 +287,30 @@ impl fmt::Debug for Ipv6MembershipRequest {
...
-    mem::swap(dst, &mut remainder);
+    ptr::copy_nonoverlapping(src as *const T as *const u8, dst[..srclen].as_mut_ptr(), srclen);
+
+    &mut dst[srclen..]
+}
+
+/// Fills `dst` with `len` zero bytes and returns the remainder of the slice.
+///
+/// Panics when `len >= dst.len()`.
+fn pad_bytes(len: usize, dst: &mut [u8]) -> &mut [u8] {
```
Comment (asomers) [inline src/sys/socket/mod.rs]: Much nicer than the previous version.  I like.

File: test/sys/test_socket.rs [hunk 8]
```diff
@@ -167,6 +167,42 @@ pub fn test_scm_rights() {
...
+    let thread = thread::spawn(move || {
+        let mut buf = [0u8; 8];
+        let iovec = [IoVec::from_mut_slice(&mut buf)];
+        let mut space = CmsgSpace::<[RawFd; 2]>::new();
+        let msg = recvmsg(receive.as_raw_fd(), &iovec, Some(&mut space), MsgFlags::empty()).unwrap();
+        assert!(!msg.flags.intersects(MsgFlags::MSG_TRUNC | MsgFlags::MSG_CTRUNC));
+
+        let mut cmsgs = msg.cmsgs();
+        match cmsgs.next() {
+            Some(ControlMessage::ScmRights(fds)) => assert_eq!(fds.len(), 2, "unexpected fd count (expected 2 fds)"),
```
Comment (asomers) [inline test/sys/test_socket.rs]: 80 chars per line, please.

File: src/sys/socket/mod.rs (hunk 6 above)
Comment (jonas-schievink) [reply src/sys/socket/mod.rs]: The problem is that this is reading the bytes of an arbitrary `T`, including its padding. If reading the bytes from a `T` is safe, then so is this function. It doesn't create any uninitialized memory or slices.

AFAIK, LLVM considers reads of padding bytes `undef`, which would be unsafe, but I don't know if rustc makes it safe in some way (eg. by providing its own padding members that read as junk instead of `undef`).

Comment (asomers) [reply src/sys/socket/mod.rs]: So the unsafe part is that it's effectively transmuting the `T`.  Transmutation is unsafe regardless of padding issues.

Comment (jonas-schievink) [reply src/sys/socket/mod.rs]: I don't think transmutation to just bytes is unsafe except when padding is involved (as there's no way to read data that isn't valid as a `u8`), but I've clarified what's going on here

**Comment by jonas-schievink** [comment]
```
     Running /target/i686-unknown-linux-gnu/release/deps/test_aio_drop-88766c7ced1811bd
running 1 test
test test_drop ... error: An unknown error occurred
```

That doesn't look good - but also spurious

**Comment by asomers** [comment]
bors retry
