### PR TITLE
Workaround XNU bug in getifaddrs netmasks

### LINKED ISSUE #1709: `SockaddrStorage::as_sockaddr_in` incorrectly returns None sometime
On `nix 0.24.x` the following is necessary to always manage to extract the IP address (and maybe something similar is needed for IPv6, but I have not encountered the problem

```rust
/// Converts a socket addr into an IP address when possible
fn try_into_ip_addr(s: &SockaddrStorage) -> Option<std::net::IpAddr> {
    // Normal method
    let or_else = s
        .as_sockaddr_in()
        .map(|sa| sa.ip().to_be_bytes().into())
        .or_else(|| s.as_sockaddr_in6().map(|sa| sa.ip().into()));

    // Start of the fallback
    match initial_method {
        im @ Some(_) => return im,
        None => (),
    }

    let sock_addr = unsafe { s.as_ptr().as_ref()? };
    if i32::from(sock_addr.sa_family) == nix::libc::AF_INET {
        dbg!(&s);
        let sock_addr = unsafe { *s.as_ptr().cast::<nix::libc::sockaddr_in>() };
        Some(Ipv4Addr::from(sock_addr.sin_addr.s_addr).into())
    } else {
        None
    }
}
```

Maybe something about the size ? 

I'm on macOS 12 but CI also fails for every type of Linux we have, both GNU and MUSL

### PR DESCRIPTION
**Pull request by roblabla**
Fixes #1709

### CODE REVIEW

File: src/ifaddrs.rs [hunk 1]
```diff
@@ -42,11 +42,47 @@ cfg_if! {
...
+    }
+    let family = unsafe {
+        (*info.ifa_netmask).sa_family
+    };
+
+    let fixup_size = match i32::from(family) {
+        libc::AF_INET => Some(std::mem::size_of::<libc::sockaddr_in>()),
+        libc::AF_INET6 => Some(std::mem::size_of::<libc::sockaddr_in6>()),
+        _ => None
+    };
```
Comment (poliorcetics) [inline src/ifaddrs.rs:64]:
```suggestion
    let fixup_size = match i32::from(family) {
        libc::AF_INET => std::mem::size_of::<libc::sockaddr_in>(),
        libc::AF_INET6 => std::mem::size_of::<libc::sockaddr_in6>(),
        _ => return
    };
```

File: src/ifaddrs.rs [hunk 2]
```diff
@@ -42,11 +42,47 @@ cfg_if! {
...
+
+    if let Some(fixup_size) = fixup_size {
+        assert!(fixup_size < u8::MAX.into());
+        let sock = info.ifa_netmask as *mut libc::sockaddr;
+        unsafe {
+            if (*sock).sa_len < fixup_size as u8 {
+                (*sock).sa_len = fixup_size as u8;
+            }
+        }
+    }
```
Comment (poliorcetics) [inline src/ifaddrs.rs:74]:
```suggestion
    assert!(fixup_size < u8::MAX.into());
    let sock = info.ifa_netmask as *mut libc::sockaddr;
    unsafe { (*sock).sa_len = (*sock).sa_len.max(fixup_size as u8) }
```

Also, seems like `ifa_netmask` is already of the type you're casting it to ? https://docs.rs/libc/latest/x86_64-apple-darwin/libc/struct.ifaddrs.html#structfield.ifa_netmask

File: src/ifaddrs.rs [hunk 3]
```diff
@@ -42,11 +42,47 @@ cfg_if! {
     }
 }
 
+/// Workaround a bug in XNU where netmasks will always have the wrong size in
+/// the sa_len field due to the kernel ignoring trailing zeroes in the future
```
Comment (poliorcetics) [inline src/ifaddrs.rs:46]:
```suggestion
/// the `sa_len` field due to the kernel ignoring trailing zeroes in the structure
```

File: src/ifaddrs.rs [hunk 4]
```diff
@@ -42,11 +42,47 @@ cfg_if! {
...
+/// when setting the field. See https://github.com/nix-rust/nix/issues/1709#issuecomment-1199304470
+///
+/// To fix this, we overwrite sa_len to have the known (static) value of the
```
Comment (poliorcetics) [inline src/ifaddrs.rs:49]:
```suggestion
/// To fix this, we overwrite `sa_len` to have the known (static) value of the
```

**Comment by roblabla** [comment]
CI breakage seems unrelated to my MR (looks like the latest serde release broke compatibility with the version of rustc/cargo used by CI).

File: src/ifaddrs.rs [hunk 5]
```diff
@@ -42,11 +42,43 @@ cfg_if! {
...
+        libc::AF_INET => std::mem::size_of::<libc::sockaddr_in>(),
+        libc::AF_INET6 => std::mem::size_of::<libc::sockaddr_in6>(),
+        _ => return
+    };
+
+    assert!(fixup_size < u8::MAX.into());
+    let sock = info.ifa_netmask;
+    unsafe {
+        (*sock).sa_len = (*sock).sa_len.max(fixup_size as u8);
+    }
```
Comment (poliorcetics) [inline src/ifaddrs.rs:70]:
```suggestion
    let sock = info.ifa_netmask;
    if sock.is_null() {
        return
    }
    let family = unsafe {
        (*sock).sa_family
    };

    let fixup_size = match i32::from(family) {
        libc::AF_INET => std::mem::size_of::<libc::sockaddr_in>(),
        libc::AF_INET6 => std::mem::size_of::<libc::sockaddr_in6>(),
        _ => return
    };

    assert!(fixup_size < u8::MAX.into());
    unsafe {
        (*sock).sa_len = (*sock).sa_len.max(fixup_size as u8)
    };
```

Uses `sock` everywhere so it's clearer we always look at the same memnber

Comment (poliorcetics) [reply src/ifaddrs.rs:70]: Uh, it's highlighting changes I haven't made ? Sorry for that, I don't know what's happening

**Comment by asomers** [comment]
> CI breakage seems unrelated to my MR (looks like the latest serde release broke compatibility with the version of rustc/cargo used by CI).

The CI breakage was due to a Cargo bug that has since been fixed.  However, serde needs to yank their most recent release and publish a new one before things will work again.  https://github.com/serde-rs/serde/issues/2255 .

File: src/ifaddrs.rs [hunk 6]
```diff
@@ -42,11 +42,43 @@ cfg_if! {
     }
 }
 
+/// Workaround a bug in XNU where netmasks will always have the wrong size in
+/// the sa_len field due to the kernel ignoring trailing zeroes in the structure
+/// when setting the field. See https://github.com/nix-rust/nix/issues/1709#issuecomment-1199304470
+///
+/// To fix this, we overwrite `sa_len` to have the known (static) value of the
+/// structure.
+#[cfg(target_os = "macos")]
```
Comment (asomers) [inline src/ifaddrs.rs:51]: Does the bug affect iOS too?

File: src/ifaddrs.rs [hunk 7]
```diff
@@ -42,11 +42,43 @@ cfg_if! {
...
+    let fixup_size = match i32::from(family) {
+        libc::AF_INET => std::mem::size_of::<libc::sockaddr_in>(),
+        libc::AF_INET6 => std::mem::size_of::<libc::sockaddr_in6>(),
+        _ => return
+    };
+
+    assert!(fixup_size < u8::MAX.into());
+    unsafe {
+        (*sock).sa_len = (*sock).sa_len.max(fixup_size as u8);
+    }
```
Comment (asomers) [inline src/ifaddrs.rs:70]: You can avoid an extra explicit assertion like this:
```suggestion
    unsafe {
        (*sock).sa_len = (*sock).sa_len.max(u8::try_from(fixup_size).unwrap());
    }
```
However, this isn't safe.  How do you know that the memory past sa_len is actually allocated and unused?  You can't.  Instead, you should fix it by copying it to a new location.

File: src/ifaddrs.rs [hunk 8]
```diff
@@ -42,11 +42,43 @@ cfg_if! {
...
 }
 
+/// Workaround a bug in XNU where netmasks will always have the wrong size in
+/// the sa_len field due to the kernel ignoring trailing zeroes in the structure
+/// when setting the field. See https://github.com/nix-rust/nix/issues/1709#issuecomment-1199304470
+///
+/// To fix this, we overwrite `sa_len` to have the known (static) value of the
+/// structure.
+#[cfg(target_os = "macos")]
+fn workaround_xnu_bug(info: &libc::ifaddrs) {
```
Comment (asomers) [inline src/ifaddrs.rs:52]: Needs a mutable reference because you're changing the structure.  The compiler doesn't warn you because the change happens via a raw pointer, but you still need a mutable reference for safety.
```suggestion
fn workaround_xnu_bug(info: &mut libc::ifaddrs) {
```

File: src/ifaddrs.rs [hunk 9]
```diff
@@ -144,4 +176,21 @@ mod tests {
...
+                sock
+            } else {
+                continue
+            };
+            if sock.family() == Some(crate::sys::socket::AddressFamily::Inet) {
+                let _ = sock.as_sockaddr_in().unwrap();
+                return;
+            }
+        }
+        panic!("No address?");
```
Comment (asomers) [inline src/ifaddrs.rs:194]: This will panic on an IPv6-only system.  Don't do that.

File: src/ifaddrs.rs [hunk 10]
```diff
@@ -144,4 +176,21 @@ mod tests {
     fn test_getifaddrs() {
         let _ = getifaddrs();
     }
+
+    #[test]
```
Comment (asomers) [inline src/ifaddrs.rs:180]: To a casual reader, this test looks pretty pointless.  Please add a comment explaining the rationale.

**Review by asomers — CHANGES_REQUESTED** [review]
It really sticks in my craw that we have to do this, but I guess we do.  We can't fix OSX.  Don't forget to add a CHANGELOG entry.

File: src/ifaddrs.rs (hunk 6 above)
Comment (roblabla) [reply src/ifaddrs.rs:51]: I suppose so, given the kernel is the same, but I have no way to test - I don't own an iDevice.

**Comment by asomers** [comment]
Rebasing will fix ci

File: src/ifaddrs.rs (hunk 9 above)
Comment (roblabla) [reply src/ifaddrs.rs:194]: It shouldn't? There's localhost. But I can always do Inet || Inet6.

**Comment by roblabla** [comment]
I rewrote the workaround to be safer - at least, I think it's safer. It now copies the data to a new zeroed sockaddr_storage.

**Comment by roblabla** [comment]
Bump. This has been used in prod for a little while, and is, as far as I can tell, sound.

**Comment by asomers** [comment]
@roblabla you still need to rebase this, both to fix CI and to fix the conflict.

**Comment by asomers** [comment]
Looks good, but still needs a CHANGELOG entry.

File: CHANGELOG.md [hunk 11]
```diff
@@ -45,7 +45,9 @@ This project adheres to [Semantic Versioning](https://semver.org/).
   ([#1815](https://github.com/nix-rust/nix/pull/1815))
 - Fix `User::from_uid` and `User::from_name` crash on Android platform.
   ([#1824](https://github.com/nix-rust/nix/pull/1824))
-
+- Workaround XNU bug causing netmasks returned by `getifaddrs` to misbehave.
+  (#1709)
```
Comment (asomers) [inline CHANGELOG.md:49]:
```suggestion
  ([#1788](https://github.com/nix-rust/nix/pull/1788))
```

**Review by asomers — CHANGES_REQUESTED** [review]

**Review by asomers — APPROVED** [review]
bors r+
