### PR TITLE
Make sockopt_impl! public

### LINKED ISSUE #577: Ability to add custom socket options
I was looking to do the following code except using nix instead of libc:

```rust
use libc::{c_ushort, c_int, c_void, socklen_t, SOL_SOCKET, setsockopt};

const SO_ATTACH_FILTER: c_int = 26;

pub fn attach_filter(fd: RawFd, prog: Prog) -> Result<(), Error> {
    match unsafe {
              setsockopt(fd as c_int,
                         SOL_SOCKET,
                         SO_ATTACH_FILTER,
                         &prog as *const _ as *const c_void,
                         size_of_val(&prog) as socklen_t)
          } {
        0 => Ok(()),
        _ => Err(Error::last_os_error()),
    }
}
```

However nix currently doesn't support this, which is fine. However, nix doesn't expose an easy way to use it's internal macros to construct the SO_ATTACH_FILTER command. I wanted to file an issue to suggest exposing this. I'll also look into contributing my use case to nix so it's added t the library for future users.

Code source: [https://github.com/jedisct1/rust-bpf/blob/0122d0a95e6012abab0475b14cef20dbfa481704/src/bpf_linux.rs#L58](https://github.com/jedisct1/rust-bpf/blob/0122d0a95e6012abab0475b14cef20dbfa481704/src/bpf_linux.rs#L58)

### PR DESCRIPTION
**Pull request by asomers**
This allows users to define their own sockopts, instead of needing to make a PR to Nix for every single one.

Fixes #577

## Checklist:

- [x] I have read `CONTRIBUTING.md`
- [x] I have written necessary tests and rustdoc comments
- [x] A change log has been added if this PR modifies nix's API

### CODE REVIEW

File: src/sys/socket/sockopt.rs [hunk 1]
```diff
@@ -42,25 +42,33 @@ const TCP_CA_NAME_MAX: usize = 16;
...
-
-                    let res = libc::setsockopt(
+            fn set<F: std::os::unix::io::AsFd>(
+                &self,
+                fd: &F,
+                val: &$ty,
+            ) -> $crate::Result<()> {
+                use $crate::sys::socket::sockopt::Set;
+                let setter: $setter =
+                    $crate::sys::socket::sockopt::Set::new(val);
```
Comment (SteveLauC) [inline src/sys/socket/sockopt.rs:59]: Considering that it has already been imported:

```suggestion
                use $crate::sys::socket::sockopt::Set;
                let setter: $setter = Set::new(val);
```

File: src/sys/socket/sockopt.rs [hunk 2]
```diff
@@ -42,25 +42,33 @@ const TCP_CA_NAME_MAX: usize = 16;
...
+                let level = $level;
+                let flag = $flag;
+                let res = unsafe {
+                    libc::setsockopt(
                         fd.as_fd().as_raw_fd(),
```
Comment (SteveLauC) [inline src/sys/socket/sockopt.rs:64]: We can import `use std::os::unix::io::AsRawFd` in the scope as well so that users won't need to do this manually:

```
/// Users should be able to define their own sockopts.
mod sockopt_impl {
    use nix::sys::socket::{
        getsockopt, setsockopt, socket, AddressFamily, SockFlag, SockProtocol,
        SockType,
    };
    use std::os::unix::io::AsRawFd; // Users do not need to handle this
```

File: src/sys/socket/sockopt.rs [hunk 3]
```diff
@@ -88,43 +96,52 @@ macro_rules! setsockopt_impl {
...
-                    let mut getter: $getter = Get::uninit();
-
-                    let res = libc::getsockopt(
+            fn get<F: std::os::unix::io::AsFd>(
+                &self,
+                fd: &F,
+            ) -> $crate::Result<$ty> {
+                use $crate::sys::socket::sockopt::Get;
+                let mut getter: $getter =
+                    $crate::sys::socket::sockopt::Get::uninit();
```
Comment (SteveLauC) [inline src/sys/socket/sockopt.rs:112]: Same here

File: src/sys/socket/sockopt.rs [hunk 4]
```diff
@@ -88,43 +96,52 @@ macro_rules! setsockopt_impl {
...
+                let level = $level;
+                let flag = $flag;
+                let res = unsafe {
+                    libc::getsockopt(
                         fd.as_fd().as_raw_fd(),
```
Comment (SteveLauC) [inline src/sys/socket/sockopt.rs:117]: Same here

File: src/sys/socket/sockopt.rs [hunk 5]
```diff
@@ -1727,15 +1775,14 @@ impl<'a> Set<'a, OsString> for SetOsString<'a> {
 }
 
 /// Getter for a `CString` value.
-#[cfg(apple_targets)]
-#[cfg(feature = "net")]
-struct GetCString<T: AsMut<[u8]>> {
+// Hide the docs, because it's an implementation detail of `sockopt_impl!`
+#[doc(hidden)]
+#[derive(Debug)]
+pub struct GetCString<T: AsMut<[u8]>> {
```
Comment (SteveLauC) [inline src/sys/socket/sockopt.rs:1781]: Currently this `Get` impl is directly used in the `sockopt_impl!` implementation:

```rs
#[cfg(apple_targets)]
#[cfg(feature = "net")]
sockopt_impl!(
    /// Get the utun interface name.
    UtunIfname,
    GetOnly,
    libc::SYSPROTO_CONTROL,
    libc::UTUN_OPT_IFNAME,
    CString,
    GetCString<[u8; libc::IFNAMSIZ]> // NOTE
);
```

because we don't have such conversion branches for it:

```rs
macro_rules! sockopt_impl {
    ($(#[$attr:meta])* $name:ident, GetOnly, $level:expr, $flag:path, CString) => {
        sockopt_impl!($(#[$attr])*
                      $name, GetOnly, $level, $flag, bool, $crate::sys::socket::sockopt::GetCString);
    ($(#[$attr:meta])* $name:ident, SetOnly, $level:expr, $flag:path, CString) => {
        sockopt_impl!($(#[$attr])*
                      $name, GetOnly, $level, $flag, bool, $crate::sys::socket::sockopt::SetCString);
    };
```

So we should probably not hide it in the doc, but it is barely used, and we can fix this if becomes commonly used in the future so hiding it still looks good to me

File: test/sys/test_sockopt.rs [hunk 6]
```diff
@@ -1047,3 +1047,54 @@ fn test_ipv6_recv_traffic_class_opts() {
...
     );
 }
+
+/// Users should be able to define their own sockopts.
+mod sockopt_impl {
+    use nix::sys::socket::{
+        getsockopt, setsockopt, socket, AddressFamily, SockFlag, SockProtocol,
+        SockType,
+    };
+    use std::os::unix::io::AsRawFd;
```
Comment (SteveLauC) [inline test/sys/test_sockopt.rs:1057]: This can be removed once we import it in the Get/Set function body

**Review by SteveLauC — COMMENTED** [review]
Left some comments

File: src/sys/socket/sockopt.rs (hunk 2 above)
Comment (asomers) [reply src/sys/socket/sockopt.rs:64]: Oh good catch.  I didn't notice that.

File: src/sys/socket/sockopt.rs (hunk 1 above)
Comment (asomers) [reply src/sys/socket/sockopt.rs]: done

File: src/sys/socket/sockopt.rs (hunk 5 above)
Comment (asomers) [reply src/sys/socket/sockopt.rs]: Oh, I guess I didn't need to make that one pub.

**Review by SteveLauC — APPROVED** [review]
Thanks!
